// Single source of truth for the studio tool suite: order, copy, and free/locked status.
// Home (marketing showcase), Tools (free tools page), and Dashboard (logged-in studio) all render from this list.
export const STUDIO_TOOLS = [
  {
    slug: 'tuner',
    emoji: '🎙',
    title: 'Tuner',
    description: 'Chromatic and instrument tuner — Guitar (Standard + Drop D), Bass, and Ukulele. Listens through your mic, nothing recorded or sent anywhere.',
    href: '/studio/tuner',
    free: true,
  },
  {
    slug: 'metronome',
    emoji: '🥁',
    title: 'Metronome',
    description: 'Precise click track with tap tempo and adjustable time signature. No account needed — open and play.',
    href: '/studio/metronome',
    free: true,
  },
  {
    slug: 'chord-scale-explorer',
    emoji: '🎵',
    title: 'Chord & Scale Explorer',
    description: 'Every chord and scale across every position on Ukulele, Tenor Guitar, Guitarlele, Acoustic Guitar, and Bass.',
    href: '/tools/chord-scale-explorer',
    free: true,
  },
  {
    slug: 'chord-charts',
    emoji: '🎸',
    title: 'Chord Chart Builder',
    description: 'Print-ready chord charts in the Rainbow Hearts style — full chart, bass/chords, and lyrics sheets.',
    href: '/studio/chord-charts',
    free: false,
  },
  {
    slug: 'tab-studio',
    emoji: '🎼',
    title: 'Tab Builder',
    description: 'Build bass and guitar tab riffs on a fret grid, hear them play back, and export as ASCII or .tab.json.',
    href: '/studio/tab-studio',
    free: false,
  },
  {
    slug: 'tab-sheet',
    emoji: '📋',
    title: 'Tab Sheet',
    description: 'Compile saved tab riffs into a printable arrangement for a song. Pick, reorder, and print your full tab chart.',
    href: '/studio/tab-sheet',
    free: false,
  },
  {
    slug: 'groove-builder',
    emoji: '🥁',
    title: 'Groove Builder',
    description: 'Capture drum grooves on a click grid — straight or triplet feel, any time signature, 1–5 instrument rows.',
    href: '/studio/groove-builder',
    free: false,
  },
  {
    slug: 'groove-sheet',
    emoji: '📄',
    title: 'Groove Sheet',
    description: 'Compile saved grooves into a printable drum chart for a song. Reorder, annotate, and print for rehearsal.',
    href: '/studio/groove-sheet',
    free: false,
  },
  {
    slug: 'setlists',
    emoji: '🎵',
    title: 'Set Lists',
    description: 'Build shareable set lists from your song library. Share a link — anyone pulls up full charts on a tablet at the gig.',
    href: '/studio/setlists',
    free: false,
  },
  {
    slug: 'heartbeats',
    emoji: '📚',
    title: 'Heart Beats Practice App',
    description: 'Daily practice cards, streaks, badges, and lesson tracking for students. Keeps the routine fun.',
    href: null,
    free: false,
    sso: true,
  },
]
